<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, formatTime, statusType } from '../api'
import { errorText } from '../feedback'
const summary = ref<any>({ nodes: {}, tasks: {} }); const tasks = ref<any[]>([]); const loading = ref(false); const error = ref('')
async function load() { loading.value = true; error.value = ''; try { [summary.value, tasks.value] = await Promise.all([api<any>('/dashboard/summary'), api<any[]>('/dashboard/recent-tasks')]) } catch (reason) { error.value = errorText(reason, '运行总览加载失败') } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="page-head"><div><h1>运行总览</h1><p>当前节点、维护包与任务运行态势</p></div><el-button :loading="loading" @click="load">刷新数据</el-button></div>
<el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><el-button link @click="load">重试</el-button></el-alert>
<div v-loading="loading"><div class="metric-grid"><div class="metric"><div class="metric-label">节点总数</div><div class="metric-value">{{ summary.nodes.total || 0 }}</div><div class="metric-detail">在线 {{ summary.nodes.online || 0 }} · 离线 {{ summary.nodes.offline || 0 }}</div></div><div class="metric"><div class="metric-label">维护包</div><div class="metric-value">{{ summary.packages || 0 }}</div><div class="metric-detail">当前有效 Revision</div></div><div class="metric"><div class="metric-label">运行中任务</div><div class="metric-value">{{ summary.tasks.RUNNING || 0 }}</div><div class="metric-detail">节点间并发 · 节点内串行</div></div><div class="metric"><div class="metric-label">失败任务</div><div class="metric-value">{{ summary.tasks.FAILED || 0 }}</div><div class="metric-detail">可按失败节点 Retry</div></div></div>
<div class="panel"><div class="panel-title"><h2>最近任务</h2><router-link to="/tasks">查看全部</router-link></div><el-table :data="tasks" empty-text="暂无任务"><el-table-column prop="id" label="Task ID" min-width="260"><template #default="s"><router-link :to="`/tasks/${s.row.id}`" class="mono">{{ s.row.id }}</router-link></template></el-table-column><el-table-column prop="package_name" label="维护包" /><el-table-column prop="status" label="状态"><template #default="s"><el-tag :type="statusType(s.row.status)">{{ s.row.status }}</el-tag></template></el-table-column><el-table-column label="节点"><template #default="s">{{ s.row.success_count }}/{{ s.row.target_node_count }}</template></el-table-column><el-table-column label="创建时间" min-width="170"><template #default="s">{{ formatTime(s.row.created_at) }}</template></el-table-column></el-table></div></div></template>
