<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { api, formatTime, statusType } from '../api'
const nodes = ref<any[]>([]); const pending = ref<any[]>([]); const loading = ref(false)
async function load() { [nodes.value, pending.value] = await Promise.all([api<any[]>('/nodes'), api<any[]>('/nodes/pending')]) }
async function refresh() { loading.value = true; try { nodes.value = await api<any[]>('/nodes/refresh', { method: 'POST' }); ElMessage.success('节点状态已刷新') } finally { loading.value = false } }
async function accept(id:string) { await api(`/nodes/pending/${encodeURIComponent(id)}/accept`, { method: 'POST' }); ElMessage.success(`已接受 ${id}`); load() }
async function reject(id:string) { await ElMessageBox.confirm(`确认拒绝 Pending Key ${id}？`, '拒绝节点', { type: 'warning' }); await api(`/nodes/pending/${encodeURIComponent(id)}/reject`, { method: 'POST' }); load() }
async function toggle(row:any) { await api(`/nodes/${encodeURIComponent(row.id)}`, { method: 'PATCH', body: JSON.stringify({ enabled: !row.enabled }) }); load() }
async function editRoles(row:any) { const result = await ElMessageBox.prompt('多个角色使用英文逗号分隔', '人工修正角色', { inputValue: row.roles.join(',') }); await api(`/nodes/${encodeURIComponent(row.id)}`, { method: 'PATCH', body: JSON.stringify({ roles: result.value.split(',').map((v:string)=>v.trim()).filter(Boolean) }) }); load() }
onMounted(load)
</script>
<template><div class="page-head"><div><h1>节点中心</h1><p>管理 Salt Minion、在线状态与业务角色</p></div><el-button type="primary" :loading="loading" @click="refresh">立即探测</el-button></div>
<div v-if="pending.length" class="panel"><div class="panel-title"><h2>Pending Keys</h2><el-tag type="warning">{{ pending.length }} 待处理</el-tag></div><el-table :data="pending"><el-table-column prop="id" label="Minion ID" /><el-table-column width="190"><template #default="s"><el-button type="primary" link @click="accept(s.row.id)">接受</el-button><el-button type="danger" link @click="reject(s.row.id)">拒绝</el-button></template></el-table-column></el-table></div>
<div class="panel"><div class="panel-title"><h2>已接入节点</h2><span class="muted">Disabled 节点不可被任务选择</span></div><el-table :data="nodes" empty-text="尚未接入节点"><el-table-column prop="hostname" label="Hostname" /><el-table-column prop="management_ip" label="管理 IP" /><el-table-column label="角色" min-width="180"><template #default="s"><el-tag v-for="role in s.row.roles" :key="role" size="small" style="margin-right:5px">{{ role }}</el-tag><span v-if="!s.row.roles.length">—</span></template></el-table-column><el-table-column label="在线"><template #default="s"><el-tag :type="statusType(s.row.online_status)">{{ s.row.online_status }}</el-tag></template></el-table-column><el-table-column label="可用"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{ s.row.enabled?'Enabled':'Disabled' }}</el-tag></template></el-table-column><el-table-column label="最近探测" min-width="170"><template #default="s">{{ formatTime(s.row.last_check_time) }}</template></el-table-column><el-table-column label="操作" width="200"><template #default="s"><el-button link @click="editRoles(s.row)">角色</el-button><el-button link :type="s.row.enabled?'warning':'success'" @click="toggle(s.row)">{{ s.row.enabled?'禁用':'启用' }}</el-button></template></el-table-column></el-table></div></template>
