<script setup lang="ts">
import { onBeforeUnmount,onMounted,ref } from 'vue';import { useRoute } from 'vue-router';import { ElMessage } from 'element-plus';import { api,formatTime,statusType } from '../api'
const route=useRoute();const task=ref<any>();const logs=ref('');const selected=ref<any>();let timer:number|undefined;let source:EventSource|undefined
async function load(){task.value=await api(`/tasks/${route.params.id}`)}
async function cancel(node:any){await api(`/tasks/${task.value.id}/nodes/${node.id}/cancel`,{method:'POST'});ElMessage.success('排队节点已取消');load()}
async function retry(node:any){await api(`/tasks/${task.value.id}/nodes/${node.id}/retry`,{method:'POST'});ElMessage.success('失败节点已重新入队');load()}
// 服务端支持 Last-Event-ID 断点续传；当前页面在 error 时主动关闭，因此尚未实现自动重连。
function openLog(node:any,attempt:any,step:any){source?.close();logs.value='';selected.value={node,attempt,step};const base=`/api/v1/tasks/${task.value.id}/nodes/${node.id}/attempts/${attempt.id}/steps/${step.id}/logs/stream`;source=new EventSource(`${base}?stream=stdout`,{withCredentials:true});source.addEventListener('log',(event:any)=>{logs.value+=JSON.parse(event.data).data});source.addEventListener('end',()=>source?.close());source.onerror=()=>source?.close()}
onMounted(async()=>{await load();timer=window.setInterval(load,3000)});onBeforeUnmount(()=>{if(timer)clearInterval(timer);source?.close()})
</script>
<template><template v-if="task"><div class="page-head"><div><h1>任务详情</h1><p class="mono">{{ task.id }}</p></div><el-tag size="large" :type="statusType(task.status)">{{ task.status }}</el-tag></div><div class="metric-grid"><div class="metric"><div class="metric-label">维护包</div><div class="metric-value" style="font-size:18px">{{ task.package_name }}</div><div class="metric-detail">Revision v{{ task.package_revision }}</div></div><div class="metric"><div class="metric-label">目标节点</div><div class="metric-value">{{ task.target_node_count }}</div></div><div class="metric"><div class="metric-label">成功</div><div class="metric-value">{{ task.success_count }}</div></div><div class="metric"><div class="metric-label">失败</div><div class="metric-value">{{ task.failed_count }}</div></div></div>
<div class="panel"><div class="panel-title"><h2>节点执行</h2><span class="muted">创建于 {{ formatTime(task.created_at) }}</span></div><el-collapse><el-collapse-item v-for="node in task.nodes" :key="node.id"><template #title><strong style="width:220px">{{ node.hostname }}</strong><el-tag :type="statusType(node.status)">{{ node.status }}</el-tag><span v-if="node.failure_reason" style="margin-left:14px;color:#c2410c">{{ node.failure_reason }}</span></template><div v-for="attempt in node.attempts" :key="attempt.id" class="panel" style="box-shadow:none"><div class="panel-title"><h2>Attempt {{ attempt.attempt_no }}</h2><el-tag :type="statusType(attempt.status)">{{ attempt.status }}</el-tag></div><el-table :data="attempt.steps"><el-table-column prop="sequence" label="#" width="55" /><el-table-column prop="name" label="Step" /><el-table-column prop="type" label="Executor" /><el-table-column label="状态"><template #default="s"><el-tag size="small" :type="statusType(s.row.status)">{{ s.row.status }}</el-tag></template></el-table-column><el-table-column prop="exit_code" label="Exit" width="65" /><el-table-column label="日志" width="90"><template #default="s"><el-button link @click="openLog(node,attempt,s.row)">查看</el-button></template></el-table-column></el-table></div><div class="form-actions"><el-button v-if="node.status==='WAITING'" @click="cancel(node)">取消排队</el-button><el-button v-if="node.status==='FAILED'" type="primary" @click="retry(node)">Retry</el-button></div></el-collapse-item></el-collapse></div><div v-if="selected" class="panel"><div class="panel-title"><h2>实时日志 · {{ selected.node.hostname }} / {{ selected.step.name }}</h2><el-button link @click="logs=''">清空显示</el-button></div><div class="log-viewer">{{ logs || '等待日志输出…' }}</div></div></template></template>
