<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';import { useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import { api } from '../api'
const router=useRouter();const packages=ref<any[]>([]);const nodes=ref<any[]>([]);const preview=ref<any>();const submitting=ref(false)
const form=reactive({package_id:'',node_ids:[] as string[],role_names:[] as string[],remark:'',confirmed_warnings:[] as string[]})
const enabledNodes=computed(()=>nodes.value.filter(n=>n.enabled))
onMounted(async()=>{[packages.value,nodes.value]=await Promise.all([api<any[]>('/packages'),api<any[]>('/nodes')])})
// Preview 只用于展示确认快照；Create 会在服务端再次校验 Package Revision 和节点状态。
async function buildPreview(){preview.value=await api<any>('/tasks/preview',{method:'POST',body:JSON.stringify({package_id:form.package_id,node_ids:form.node_ids,role_names:form.role_names})});form.confirmed_warnings=[]}
// 每次用户点击产生一个新 Key；网络层若重放同一次请求必须复用该 Key 才能取得原 Task。
async function submit(){if(!preview.value)return;const required:string[]=[...new Set<string>(preview.value.warnings.map((w:any)=>String(w.type)))];if(required.some(x=>!form.confirmed_warnings.includes(x))){ElMessage.warning('请先确认全部风险警告');return}submitting.value=true;try{const task=await api<any>('/tasks',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(form)});ElMessage.success('任务已创建');router.push(`/tasks/${task.id}`)}finally{submitting.value=false}}
</script>
<template><div class="page-head"><div><h1>创建维护任务</h1><p>选择 Package 与实际目标节点，并在执行前确认快照</p></div></div><div class="two-column"><div class="panel"><div class="panel-title"><h2>任务参数</h2></div><el-form label-position="top"><el-form-item label="维护包"><el-select v-model="form.package_id" style="width:100%" placeholder="选择当前 Revision"><el-option v-for="p in packages" :key="p.id" :label="`${p.name} · v${p.revision}`" :value="p.id" /></el-select></el-form-item><el-form-item label="按角色选择"><el-checkbox-group v-model="form.role_names"><el-checkbox v-for="r in ['compute','network','controller','ceph']" :key="r" :value="r">{{ r }}</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="直接选择节点"><el-select v-model="form.node_ids" multiple filterable style="width:100%"><el-option v-for="n in enabledNodes" :key="n.id" :label="`${n.hostname} · ${n.online_status}`" :value="n.id" /></el-select></el-form-item><el-form-item label="Remark"><el-input v-model="form.remark" type="textarea" :rows="3" maxlength="2000" show-word-limit /></el-form-item><div class="form-actions"><el-button type="primary" :disabled="!form.package_id" @click="buildPreview">生成确认快照</el-button></div></el-form></div>
<div class="panel"><div class="panel-title"><h2>执行确认</h2><span class="muted">创建时再次校验</span></div><el-empty v-if="!preview" description="请先生成确认快照" /><template v-else><el-descriptions border :column="1"><el-descriptions-item label="Package">{{ preview.package.name }} · v{{ preview.package.revision }}</el-descriptions-item><el-descriptions-item label="实际节点">{{ preview.nodes.map((n:any)=>n.hostname).join(', ') }}</el-descriptions-item></el-descriptions><div v-for="warning in preview.warnings" :key="`${warning.node_id}-${warning.type}`" class="warning-box" style="margin-top:12px"><el-checkbox v-model="form.confirmed_warnings" :value="warning.type">确认 {{ warning.node_id }}：{{ warning.message }}</el-checkbox></div><div class="form-actions"><el-button type="danger" :loading="submitting" @click="submit">立即执行</el-button></div></template></div></div></template>
